### ISSUE TITLE
OpenSSL requirement is onerous (use native TLS instead)

### ISSUE THREAD

**Issue by chris-morgan** [rushmorem/publicsuffix#1]
Switching from reqwest to hyper had the effect of introducing an OpenSSL requirement on Windows and macOS that wasn’t there before, and getting OpenSSL working properly on Windows is a nuisance. reqwest does what a normal person would expect: it uses the platform’s native TLS implementation, via the native-tls crate.

It’d be good for this crate to switch back to using native-tls so that it can be used on Windows without having to have OpenSSL set up on platforms where it’s tricky to do so.

**Comment by rushmorem** [comment]
I would love to switch back to `reqwest`. The only reason I switched to `hyper` is because it allows me to `set_read_timeout` and `set_write_timeout`. I was running into an issue where a request would hang for a long time if the connection was bad. If there is a way to get around this while using `reqwest` I will happily switch back.

**Comment by rushmorem** [comment]
I have disabled all Hyper features, which include `ssl`. We are now using `native-tls` directly. Thank you for bringing this up. I think a full blown HTTP library was overkill for our use case anyway.
